services:
  muse-proxy:
    build: .
    container_name: muse-proxy
    restart: unless-stopped
    ports:
      - "9797:9797"
      - "9443:9443"
    environment:
      - PROXY_PORT=9797
      - SSL_PROXY_PORT=9443
      - ADMIN_PASSWORD=admin1234
    volumes:
      - ./license.lic:/opt/muse/license.lic
      - ./data:/opt/muse/data